version: '3.8'

services:
  auth-service:
    build: .
    container_name: samebi_auth_service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=7d
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - ALLOWED_ORIGINS=https://dashboard.samebi.net,https://api.samebi.net
      - LOG_LEVEL=info
    networks:
      - samebi_network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "coolify.managed=true"
      - "coolify.name=samebi-auth-service"
      - "coolify.http.domain=auth.samebi.net"
      - "coolify.http.port=3001"

networks:
  samebi_network:
    external: true

