version: '3.8'

services:
  screening-tool:
    build: .
    container_name: screening-tool-samebi
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.screening-tool.rule=Host(`screening.samebi.net`)"
      - "traefik.http.routers.screening-tool.tls=true"
      - "traefik.http.routers.screening-tool.tls.certresolver=letsencrypt"
      - "traefik.http.services.screening-tool.loadbalancer.server.port=80"
